"""Add Industrial Operations Core schemas

Revision ID: 3416e09ebcc3
Revises: 7a8b9c0d1e2f
Create Date: 2026-08-29 12:28:56.233971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3416e09ebcc3'
down_revision: Union[str, None] = '7a8b9c0d1e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_card_amendments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_card_id', sa.UUID(), nullable=False),
    sa.Column('amended_by_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.String(length=4000), nullable=True),
    sa.Column('new_value', sa.String(length=4000), nullable=True),
    sa.Column('amendment_reason', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['amended_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_card_execution_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_card_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=False),
    sa.Column('operator_name', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_card_labour',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_card_id', sa.UUID(), nullable=False),
    sa.Column('technician_name', sa.String(length=255), nullable=False),
    sa.Column('trade', sa.String(length=100), nullable=False),
    sa.Column('hours_spent', sa.Float(), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('audit_logs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('business_audit_logs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('business_audit_logs', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.add_column('departments', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('departments', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('departments', 'site_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('departments', 'hod_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('departments', 'sla_hours_default',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'24'"))
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=False)
    op.create_index(op.f('ix_departments_hod_id'), 'departments', ['hod_id'], unique=False)
    op.create_index(op.f('ix_departments_site_id'), 'departments', ['site_id'], unique=False)
    op.drop_constraint('fk_departments_hod_id', 'departments', type_='foreignkey')
    op.alter_column('employee_profiles', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('employee_profiles', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('job_card_action_logs', sa.Column('state_from', sa.String(length=50), nullable=True))
    op.add_column('job_card_action_logs', sa.Column('state_to', sa.String(length=50), nullable=True))
    op.alter_column('job_card_action_logs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('job_card_action_logs', 'job_card_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('job_card_action_logs', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('job_card_attachments', sa.Column('file_type', sa.String(length=100), nullable=True))
    op.add_column('job_card_attachments', sa.Column('file_size_kb', sa.Float(), nullable=True))
    op.alter_column('job_card_attachments', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('job_card_attachments', 'job_card_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('job_card_collaborators', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('job_card_collaborators', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('job_card_comments', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('job_card_comments', 'job_card_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('job_card_comments', 'author_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('job_card_parts', sa.Column('part_number', sa.String(length=100), nullable=True))
    op.add_column('job_card_parts', sa.Column('is_material', sa.Boolean(), nullable=False))
    op.alter_column('job_card_parts', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('job_card_parts', 'job_card_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('job_cards', sa.Column('job_number', sa.String(length=50), nullable=True))
    op.add_column('job_cards', sa.Column('workshop_code', sa.String(length=100), nullable=True))
    op.add_column('job_cards', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('job_cards', sa.Column('plant_area', sa.String(length=255), nullable=True))
    op.add_column('job_cards', sa.Column('required_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_cards', sa.Column('job_type', sa.String(length=100), nullable=True))
    op.add_column('job_cards', sa.Column('job_instruction', sa.String(length=4000), nullable=True))
    op.add_column('job_cards', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_cards', sa.Column('assigned_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_cards', sa.Column('assigned_personnel', sa.String(length=1000), nullable=True))
    op.add_column('job_cards', sa.Column('estimated_hours', sa.Float(), nullable=False))
    op.add_column('job_cards', sa.Column('estimated_cost', sa.Float(), nullable=False))
    op.add_column('job_cards', sa.Column('labour_details', sa.String(length=2000), nullable=True))
    op.add_column('job_cards', sa.Column('completion_notes', sa.String(length=4000), nullable=True))
    op.add_column('job_cards', sa.Column('requester_confirmed', sa.Boolean(), nullable=False))
    op.add_column('job_cards', sa.Column('requester_notes', sa.String(length=2000), nullable=True))
    op.add_column('job_cards', sa.Column('requester_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_cards', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_cards', sa.Column('closure_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_cards', sa.Column('closed_by_id', sa.UUID(), nullable=True))
    op.alter_column('job_cards', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('job_cards', 'department_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('job_cards', 'machine_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('job_cards', 'creator_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('job_cards', 'maintenance_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('job_cards', 'approver_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('job_cards', 'supervisor_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_foreign_key(None, 'job_cards', 'users', ['closed_by_id'], ['id'])
    op.create_foreign_key(None, 'job_cards', 'departments', ['requesting_department_id'], ['id'])
    op.create_foreign_key(None, 'job_cards', 'departments', ['responsible_department_id'], ['id'])
    op.alter_column('machine_requisitions', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('machine_requisitions', 'department_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('machine_requisitions', 'requester_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('machine_requisitions', 'purpose',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    op.alter_column('machine_requisitions', 'machine_type_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('machine_requisitions', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('machine_requisitions', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('machine_requisitions', 'estimated_duration_hours',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('machine_requisitions', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('machine_requisitions', 'operator_required',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('machine_requisitions', 'estimated_cost',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('machine_requisitions', 'approver_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'machine_requisitions', ['requisition_number'])
    op.create_foreign_key(None, 'machine_requisitions', 'users', ['equipment_checker_id'], ['id'])
    op.create_foreign_key(None, 'machine_requisitions', 'machines', ['machine_id'], ['id'])
    op.create_foreign_key(None, 'machine_requisitions', 'users', ['inspector_id'], ['id'])
    op.create_foreign_key(None, 'machine_requisitions', 'job_cards', ['job_card_id'], ['id'])
    op.create_foreign_key(None, 'machine_requisitions', 'users', ['dispatcher_id'], ['id'])
    op.create_foreign_key(None, 'machine_requisitions', 'users', ['scheduler_id'], ['id'])
    op.create_foreign_key(None, 'machine_requisitions', 'departments', ['collaborating_department_id'], ['id'])
    op.create_foreign_key(None, 'machine_requisitions', 'users', ['dept_approver_id'], ['id'])
    op.alter_column('machine_reservations', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('machine_reservations', 'requisition_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('machine_reservations', 'machine_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('machine_reservations', 'start_time',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('machine_reservations', 'end_time',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('machine_reservations', 'start_hours',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('machine_reservations', 'end_hours',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('machine_types', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('machines', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('machines', 'machine_type_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('machines', 'current_hour_meter',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('organizations', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('permissions', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('positions', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('positions', 'department_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_positions_department_id'), 'positions', ['department_id'], unique=False)
    op.alter_column('role_permissions', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('role_permissions', 'role_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('role_permissions', 'permission_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('roles', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('sections', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('sections', 'department_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('sections', 'supervisor_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_sections_department_id'), 'sections', ['department_id'], unique=False)
    op.create_index(op.f('ix_sections_supervisor_id'), 'sections', ['supervisor_id'], unique=False)
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.alter_column('sites', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('sites', 'organization_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_sites_organization_id'), 'sites', ['organization_id'], unique=False)
    op.alter_column('sms_messages', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('teams', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('teams', 'section_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('teams', 'team_lead_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_teams_section_id'), 'teams', ['section_id'], unique=False)
    op.create_index(op.f('ix_teams_team_lead_id'), 'teams', ['team_lead_id'], unique=False)
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.alter_column('user_roles', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('user_roles', 'role_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('users', 'department_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('users', 'section_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('users', 'team_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('users', 'position_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('users', 'supervisor_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_employee_number'), 'users', ['employee_number'], unique=True)
    op.create_index(op.f('ix_users_position_id'), 'users', ['position_id'], unique=False)
    op.create_index(op.f('ix_users_section_id'), 'users', ['section_id'], unique=False)
    op.create_index(op.f('ix_users_supervisor_id'), 'users', ['supervisor_id'], unique=False)
    op.create_index(op.f('ix_users_team_id'), 'users', ['team_id'], unique=False)
    op.alter_column('work_packages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('work_packages', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_packages', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('work_packages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index(op.f('ix_users_team_id'), table_name='users')
    op.drop_index(op.f('ix_users_supervisor_id'), table_name='users')
    op.drop_index(op.f('ix_users_section_id'), table_name='users')
    op.drop_index(op.f('ix_users_position_id'), table_name='users')
    op.drop_index(op.f('ix_users_employee_number'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.alter_column('users', 'supervisor_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('users', 'position_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('users', 'team_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('users', 'section_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('users', 'department_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('user_roles', 'role_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('user_roles', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.create_foreign_key(None, 'teams', 'users', ['team_lead_id'], ['id'])
    op.drop_index(op.f('ix_teams_team_lead_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_section_id'), table_name='teams')
    op.alter_column('teams', 'team_lead_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('teams', 'section_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('teams', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('sms_messages', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_sites_organization_id'), table_name='sites')
    op.alter_column('sites', 'organization_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('sites', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.create_foreign_key(None, 'sections', 'users', ['supervisor_id'], ['id'])
    op.drop_index(op.f('ix_sections_supervisor_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_department_id'), table_name='sections')
    op.alter_column('sections', 'supervisor_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('sections', 'department_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('sections', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('roles', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('role_permissions', 'permission_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('role_permissions', 'role_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('role_permissions', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_positions_department_id'), table_name='positions')
    op.alter_column('positions', 'department_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('positions', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('permissions', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('organizations', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('machines', 'current_hour_meter',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('machines', 'machine_type_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('machines', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('machine_types', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('machine_reservations', 'end_hours',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('machine_reservations', 'start_hours',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('machine_reservations', 'end_time',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('machine_reservations', 'start_time',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('machine_reservations', 'machine_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('machine_reservations', 'requisition_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('machine_reservations', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_constraint(None, 'machine_requisitions', type_='foreignkey')
    op.drop_constraint(None, 'machine_requisitions', type_='foreignkey')
    op.drop_constraint(None, 'machine_requisitions', type_='foreignkey')
    op.drop_constraint(None, 'machine_requisitions', type_='foreignkey')
    op.drop_constraint(None, 'machine_requisitions', type_='foreignkey')
    op.drop_constraint(None, 'machine_requisitions', type_='foreignkey')
    op.drop_constraint(None, 'machine_requisitions', type_='foreignkey')
    op.drop_constraint(None, 'machine_requisitions', type_='foreignkey')
    op.drop_constraint(None, 'machine_requisitions', type_='unique')
    op.alter_column('machine_requisitions', 'approver_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('machine_requisitions', 'estimated_cost',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('machine_requisitions', 'operator_required',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('machine_requisitions', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('machine_requisitions', 'estimated_duration_hours',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('machine_requisitions', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('machine_requisitions', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('machine_requisitions', 'machine_type_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('machine_requisitions', 'purpose',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    op.alter_column('machine_requisitions', 'requester_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('machine_requisitions', 'department_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('machine_requisitions', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_constraint(None, 'job_cards', type_='foreignkey')
    op.drop_constraint(None, 'job_cards', type_='foreignkey')
    op.drop_constraint(None, 'job_cards', type_='foreignkey')
    op.alter_column('job_cards', 'supervisor_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('job_cards', 'approver_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('job_cards', 'maintenance_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('job_cards', 'creator_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('job_cards', 'machine_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('job_cards', 'department_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('job_cards', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('job_cards', 'closed_by_id')
    op.drop_column('job_cards', 'closure_date')
    op.drop_column('job_cards', 'verified_at')
    op.drop_column('job_cards', 'requester_confirmed_at')
    op.drop_column('job_cards', 'requester_notes')
    op.drop_column('job_cards', 'requester_confirmed')
    op.drop_column('job_cards', 'completion_notes')
    op.drop_column('job_cards', 'labour_details')
    op.drop_column('job_cards', 'estimated_cost')
    op.drop_column('job_cards', 'estimated_hours')
    op.drop_column('job_cards', 'assigned_personnel')
    op.drop_column('job_cards', 'assigned_date')
    op.drop_column('job_cards', 'approved_at')
    op.drop_column('job_cards', 'job_instruction')
    op.drop_column('job_cards', 'job_type')
    op.drop_column('job_cards', 'required_date')
    op.drop_column('job_cards', 'plant_area')
    op.drop_column('job_cards', 'location')
    op.drop_column('job_cards', 'workshop_code')
    op.drop_column('job_cards', 'job_number')
    op.alter_column('job_card_parts', 'job_card_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('job_card_parts', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('job_card_parts', 'is_material')
    op.drop_column('job_card_parts', 'part_number')
    op.alter_column('job_card_comments', 'author_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('job_card_comments', 'job_card_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('job_card_comments', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('job_card_collaborators', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('job_card_collaborators', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('job_card_attachments', 'job_card_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('job_card_attachments', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('job_card_attachments', 'file_size_kb')
    op.drop_column('job_card_attachments', 'file_type')
    op.alter_column('job_card_action_logs', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('job_card_action_logs', 'job_card_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('job_card_action_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('job_card_action_logs', 'state_to')
    op.drop_column('job_card_action_logs', 'state_from')
    op.alter_column('employee_profiles', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('employee_profiles', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.create_foreign_key('fk_departments_hod_id', 'departments', 'users', ['hod_id'], ['id'])
    op.drop_index(op.f('ix_departments_site_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_hod_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.alter_column('departments', 'sla_hours_default',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'24'"))
    op.alter_column('departments', 'hod_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('departments', 'site_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('departments', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('departments', 'is_active')
    op.alter_column('business_audit_logs', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('business_audit_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_table('job_card_labour')
    op.drop_table('job_card_execution_events')
    op.drop_table('job_card_amendments')
    # ### end Alembic commands ###
